### ISSUE TITLE
耗时统计没有生效 大佬看看是为啥啊？

### ISSUE THREAD

**Issue by jiangchao0829** [AndyM129/AMKLaunchTimeProfiler#1]
- 
![be00d9bcc18cc75c829d4899cf7ea20d](https://user-images.githubusercontent.com/117245393/199442384-e33a87af-029b-47d1-8aae-1839d21e5080.jpg)

**Comment by AndyM129** [comment]
## 结论

对于该反馈，从截图来看，应该是符合预期的



## 原因

在实践时发现，会存在「计算出的 耗时为 ≤0 」的情况，而这是不符合预期的，

所以在最终汇总、求和、取平均值时，过滤掉了这部分数据，

由您提供的截图可知（红框部分），目前仅有一次冷启动，且「被判定为无效数据」（篮框部分），

所以「日志页底部」显示了「暂无有效数据」




## 解决

您可以多 冷启动几次，然后看下平均值，例如 我们目前的测试方式：

* 安装后，连续冷启动2次，然后手动清空日志（因为 通常这两次耗时都会高于正常使用时的耗时，故排除这部分的影响）
* 继续连续冷启动10+次，手动打开日志页，可以看到统计结果

```
10 次有效数据的平均数：
--------------------------------------------------
          total time consuming: 2.508 s 
       pre-main time consuming: 1.989 s (79.30%)
           main time consuming: 0.454 s (18.08%)
   first screen time consuming: 0.066 s (2.61%)
```

<img width="837" alt="截图" src="https://user-images.githubusercontent.com/9859108/199469679-5f57bb63-26ab-4aed-98b0-517a84b17693.png">

**Comment by AndyM129** [comment]
哦哦，我刚意识到一个细节：

您这边的日志，没有统计到「首屏渲染完成」，使得没有统计到「冷启动结束的时间」，所以「总耗时为0」，以致「无有效数据」

![image](https://user-images.githubusercontent.com/9859108/199478653-d5af5b51-618e-4018-9b46-aa1f177d78a5.png)


组件中，这部分的实现，见 [UIResponder+AMKLaunchTimeProfiler.m#L83-L88](https://github.com/AndyM129/AMKLaunchTimeProfiler/blob/master/AMKLaunchTimeProfiler/Classes/Core/UIResponder+AMKLaunchTimeProfiler.m#L83-L88)

因为没有您的源码，所以无法定位具体原因了，您可以自己断点调试下，或是「发我一份能复现该问题的示例工程」



此外，您也可以在 `UIApplication.sharedApplication.delegate.window.rootViewController` 的 `-viewDidAppear:` 方法最后，手动调用如下代码，应该也能解决您遇到的问题：

```objective-c
// 注：为了考虑封装性，-firstScreenTime 被声明为了只读属性，可以通过「手动声明」来解决赋值
@interface AMKLaunchTimeProfiler (issues_1)
@property(nonatomic, assign, readwrite) NSTimeInterval firstScreenTime;
@end

// 假设这就是 UIApplication.sharedApplication.delegate.window.rootViewController 对应的类
@implementation AMKRootViewController

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    
    // 新增代码
    AMKLaunchTimeProfiler.sharedInstance.firstScreenTime = CFAbsoluteTimeGetCurrent() + kCFAbsoluteTimeIntervalSince1970;
    AMKLaunchTimeProfilerInternalLog(@"first screen time: %@", [@(AMKLaunchTimeProfiler.sharedInstance.firstScreenTime) performSelector:@selector(amkltp_formattedDateStringForSystemTimeZone)]);
    [NSNotificationCenter.defaultCenter postNotificationName:AMKLaunchTimeProfilerFirstScreenDidDisplayNotification object:AMKLaunchTimeProfiler.sharedInstance];
}

@end
```

**Comment by AndyM129** [comment]
上面是我的思路，实际写了下，提到了[`origin/test/issues#1` 分支](https://github.com/AndyM129/AMKLaunchTimeProfiler/tree/test/issues%231) 上，详见 [`commit 26be3f3`](https://github.com/AndyM129/AMKLaunchTimeProfiler/commit/26be3f392f6ba7c8a4eb640e8f93eef5f4eff1df)
